// Nepali text for the interface. Keys are the English strings used in the code; {placeholders} must be kept.
// NOTE: written by an AI assistant, so it needs review by a native Nepali speaker before public launch.
export const NE: Record<string, string> = {
  // emergency bar
  "Emergency": "आपतकालीन",
  "Emergency numbers": "आपतकालीन नम्बरहरू",
  "Police": "प्रहरी",
  "Ambulance": "एम्बुलेन्स",
  "Disaster": "विपद्",

  // levels and wording about reports
  "High reported activity": "उच्च रिपोर्ट गरिएको गतिविधि",
  "Elevated reported activity": "बढी रिपोर्ट गरिएको गतिविधि",
  "Some reports nearby": "नजिकै केही रिपोर्ट",
  "No reports in this window": "यो अवधिमा कुनै रिपोर्ट छैन",
  "High": "उच्च",
  "Elevated": "बढी",
  "Some reports": "केही रिपोर्ट",
  "None": "कुनै छैन",
  "How this is worked out": "यो कसरी निकालिएको हो",
  "a river station above its danger level, or {a}+ incidents within {k} km in the last {h} h.": "कुनै नदी स्टेशन खतरा स्तरभन्दा माथि, वा पछिल्ला {h} घण्टामा {k} कि.मि. भित्र {a}+ घटना।",
  "a station above warning level, any incident within {k} km in the last {h} h, or {a}+ incidents in your radius and time window.": "कुनै स्टेशन चेतावनी स्तरभन्दा माथि, पछिल्ला {h} घण्टामा {k} कि.मि. भित्र कुनै घटना, वा तपाईंले छानेको दायरा र अवधिमा {a}+ घटना।",
  "at least one incident in your radius and window.": "तपाईंको दायरा र अवधिमा कम्तीमा एक घटना।",
  "nothing reported.": "केही रिपोर्ट भएको छैन।",
  "This only counts official reports and readings. It is a summary of what was reported, not a forecast and not a judgement about whether it is okay to travel or stay.": "यसले आधिकारिक रिपोर्ट र मापन मात्र गणना गर्छ। यो रिपोर्ट भएका कुराको सारांश हो, पूर्वानुमान होइन, र यात्रा गर्ने वा बस्ने ठीक हो कि होइन भन्ने निर्णय पनि होइन।",
  "{n} river station above danger level within {r} km": "{r} कि.मि. भित्र {n} नदी स्टेशन खतरा स्तरभन्दा माथि",
  "{n} river stations above danger level within {r} km": "{r} कि.मि. भित्र {n} नदी स्टेशन खतरा स्तरभन्दा माथि",
  "{n} river station above warning level within {r} km": "{r} कि.मि. भित्र {n} नदी स्टेशन चेतावनी स्तरभन्दा माथि",
  "{n} river stations above warning level within {r} km": "{r} कि.मि. भित्र {n} नदी स्टेशन चेतावनी स्तरभन्दा माथि",
  "{n} incident within {k} km in the last {h} hours": "पछिल्ला {h} घण्टामा {k} कि.मि. भित्र {n} घटना",
  "{n} incidents within {k} km in the last {h} hours": "पछिल्ला {h} घण्टामा {k} कि.मि. भित्र {n} घटना",
  "{n} incident within {r} km in the last {d} days ({f} flood, {l} landslide)": "पछिल्ला {d} दिनमा {r} कि.मि. भित्र {n} घटना ({f} बाढी, {l} पहिरो)",
  "{n} incidents within {r} km in the last {d} days ({f} flood, {l} landslide)": "पछिल्ला {d} दिनमा {r} कि.मि. भित्र {n} घटना ({f} बाढी, {l} पहिरो)",
  "{n} incident within {r} km in the last 24 hours ({f} flood, {l} landslide)": "पछिल्ला २४ घण्टामा {r} कि.मि. भित्र {n} घटना ({f} बाढी, {l} पहिरो)",
  "{n} incidents within {r} km in the last 24 hours ({f} flood, {l} landslide)": "पछिल्ला २४ घण्टामा {r} कि.मि. भित्र {n} घटना ({f} बाढी, {l} पहिरो)",
  "No flood or landslide reports within {r} km in the last {d} days": "पछिल्ला {d} दिनमा {r} कि.मि. भित्र बाढी वा पहिरोको कुनै रिपोर्ट छैन",
  "No flood or landslide reports within {r} km in the last 24 hours": "पछिल्ला २४ घण्टामा {r} कि.मि. भित्र बाढी वा पहिरोको कुनै रिपोर्ट छैन",
  "No river stations within this radius, so river conditions here are not covered.": "यो दायरा भित्र कुनै नदी स्टेशन छैन, त्यसैले यहाँको नदीको अवस्था समेटिएको छैन।",
  "None of the nearby river stations have a current reading.": "नजिकका कुनै पनि नदी स्टेशनमा हालको मापन छैन।",
  "{a} of {b} nearby river stations have no current reading.": "नजिकका {b} नदी स्टेशनमध्ये {a} मा हालको मापन छैन।",
  "Only official BIPAD reports are used. Reports can be late or missing, so a quiet area is not confirmation of no hazard.": "केवल बिपदको आधिकारिक रिपोर्ट प्रयोग गरिएको छ। रिपोर्ट ढिलो वा छुट्न सक्छ, त्यसैले शान्त देखिने ठाउँ जोखिम नभएको पुष्टि होइन।",

  // filters and search
  "Map filters": "नक्सा फिल्टर",
  "Show": "देखाउनुहोस्",
  "Floods": "बाढी",
  "Landslides": "पहिरो",
  "Rain": "वर्षा",
  "Rivers": "नदीहरू",
  "Reset": "रिसेट",
  "Select every layer again and restore 7 days, 25 km and 3 h rain": "सबै तह फेरि छान्नुहोस् र ७ दिन, २५ कि.मि. र ३ घण्टाको वर्षा पुनःस्थापना गर्नुहोस्",
  "Period": "अवधि",
  "Time window": "समय अवधि",
  "Rain over": "वर्षाको अवधि",
  "Rain accumulated over": "वर्षा जम्मा भएको अवधि",
  "Radius": "दायरा",
  "{n} km": "{n} कि.मि.",
  "24 h": "२४ घण्टा",
  "3 days": "३ दिन",
  "7 days": "७ दिन",
  "14 days": "१४ दिन",
  "1 h": "१ घण्टा",
  "3 h": "३ घण्टा",
  "6 h": "६ घण्टा",
  "12 h": "१२ घण्टा",
  "Search a place · काठमाडौँ": "स्थान खोज्नुहोस् · Kathmandu",
  "Search a municipality or district": "नगरपालिका वा जिल्ला खोज्नुहोस्",
  "Reset the map and show all of Nepal": "नक्सा रिसेट गरी सम्पूर्ण नेपाल देखाउनुहोस्",
  "Reset map · show all of Nepal": "नक्सा रिसेट · सम्पूर्ण नेपाल",
  "Use my location": "मेरो स्थान प्रयोग गर्नुहोस्",
  "Browse regions": "क्षेत्र हेर्नुहोस्",
  "Browse by province, district, municipality": "प्रदेश, जिल्ला, नगरपालिका अनुसार हेर्नुहोस्",
  "Clear selected place": "छानिएको स्थान हटाउनुहोस्",
  "Clear": "हटाउनुहोस्",
  "My places": "मेरा स्थानहरू",
  "Choose a province, then a district, then a municipality": "पहिले प्रदेश, अनि जिल्ला, अनि नगरपालिका छान्नुहोस्",
  "Province": "प्रदेश",
  "District": "जिल्ला",
  "Municipality": "नगरपालिका",
  "Choose province": "प्रदेश छान्नुहोस्",
  "Choose district": "जिल्ला छान्नुहोस्",
  "Pick a province first": "पहिले प्रदेश छान्नुहोस्",
  "Choose municipality": "नगरपालिका छान्नुहोस्",
  "Pick a district first": "पहिले जिल्ला छान्नुहोस्",
  "Loading…": "लोड हुँदैछ…",
  "{d} district, {p}": "{d} जिल्ला, {p}",
  "Near {x}": "{x} नजिक",
  "Selected point": "छानिएको बिन्दु",
  "Selected place": "छानिएको स्थान",
  "Locating…": "स्थान खोज्दै…",
  "Finding your location…": "तपाईंको स्थान खोज्दै…",
  "Location is not available on this device.": "यो उपकरणमा स्थान सुविधा उपलब्ध छैन।",
  "Your location is outside Nepal. Tap the map to pick a place.": "तपाईंको स्थान नेपाल बाहिर छ। नक्सामा थिचेर स्थान छान्नुहोस्।",
  "Could not get your location. Search or tap the map instead.": "तपाईंको स्थान प्राप्त हुन सकेन। खोज्नुहोस् वा नक्सामा थिच्नुहोस्।",
  "Tap anywhere on the map to check that area": "त्यो क्षेत्र जाँच्न नक्सामा जहाँसुकै थिच्नुहोस्",

  // map legend and panels
  "Map legend": "नक्साको संकेत",
  "Reports": "रिपोर्टहरू",
  "Flood": "बाढी",
  "Landslide": "पहिरो",
  "Normal": "सामान्य",
  "Warning": "चेतावनी",
  "Danger": "खतरा",
  "No data": "तथ्याङ्क छैन",
  "Trace": "अत्यन्त थोरै",
  "Light": "हल्का",
  "Moderate": "मध्यम",
  "Heavy": "भारी",
  "Very heavy": "अति भारी",
  "Rain · last {w} h": "वर्षा · पछिल्ला {w} घण्टा",
  "Rain colour scale in millimetres: none, under 5, 5, 15.6, 64.5, 115.6 and over": "मिलिमिटरमा वर्षाको रङ स्केल: कुनै छैन, ५ भन्दा कम, ५, १५.६, ६४.५, ११५.६ र माथि",
  "Area details": "क्षेत्रको विवरण",
  "Show less": "कम देखाउनुहोस्",
  "Show details": "विवरण देखाउनुहोस्",
  "Loading map…": "नक्सा लोड हुँदैछ…",
  "Details": "विवरण",
  "Hide the details panel for a full-screen map": "पूर्ण-स्क्रिन नक्साका लागि विवरण प्यानल लुकाउनुहोस्",
  "Show the details panel": "विवरण प्यानल देखाउनुहोस्",
  "Full-screen map": "पूर्ण-स्क्रिन नक्सा",
  "Full map": "पूर्ण नक्सा",
  "Nepal right now": "अहिलेको नेपाल",
  "Tap the map where you are, or search a place, to check an area.": "आफू भएको ठाउँमा नक्सा थिच्नुहोस्, वा स्थान खोजेर क्षेत्र जाँच्नुहोस्।",
  "Choose a municipality, or tap the map, to check an area.": "नगरपालिका छान्नुहोस्, वा नक्सा थिचेर क्षेत्र जाँच्नुहोस्।",
  "reports · last {d}": "रिपोर्ट · पछिल्ला {d}",
  "floods": "बाढी",
  "landslides": "पहिरो",
  "flood": "बाढी",
  "landslide": "पहिरो",
  "rivers over warning": "चेतावनी स्तरभन्दा माथिका नदी",
  "{n} d": "{n} दिन",
  "{n} days": "{n} दिन",
  "24 hours": "२४ घण्टा",
  "last 24 hours": "पछिल्ला २४ घण्टा",
  "last {n} days": "पछिल्ला {n} दिन",
  "within {r} km": "{r} कि.मि. भित्र",
  "Rivers above warning level now": "अहिले चेतावनी स्तरभन्दा माथिका नदी",
  "No river station currently reports above its warning level.": "हाल कुनै नदी स्टेशनले चेतावनी स्तरभन्दा माथि रिपोर्ट गरेको छैन।",
  "Heaviest rain · last {w} h": "सबैभन्दा भारी वर्षा · पछिल्ला {w} घण्टा",
  "No rain recorded in the last {w} h at the {n} stations with a current reading.": "हालको मापन भएका {n} स्टेशनमा पछिल्ला {w} घण्टामा वर्षा रेकर्ड भएको छैन।",
  "{a} of {b} rain stations have a current reading": "{b} वर्षा स्टेशनमध्ये {a} मा हालको मापन छ",
  "{n} report impossible values and are hidden": "{n} ले असम्भव मान देखाएकाले लुकाइएको छ",
  "Rainfall · last {w} h": "वर्षा · पछिल्ला {w} घण्टा",
  "No rain stations with a current reading within {r} km.": "{r} कि.मि. भित्र हालको मापन भएको कुनै वर्षा स्टेशन छैन।",
  "No rain recorded in the last {w} h at the {n} reporting station within {r} km.": "{r} कि.मि. भित्रको {n} स्टेशनमा पछिल्ला {w} घण्टामा वर्षा रेकर्ड भएको छैन।",
  "No rain recorded in the last {w} h at the {n} reporting stations within {r} km.": "{r} कि.मि. भित्रका {n} स्टेशनमा पछिल्ला {w} घण्टामा वर्षा रेकर्ड भएको छैन।",
  "Wettest nearby": "नजिकको सबैभन्दा बढी वर्षा",
  "at": "मा",
  "{n} station reporting.": "{n} स्टेशनले रिपोर्ट गरिरहेको छ।",
  "{n} stations reporting.": "{n} स्टेशनले रिपोर्ट गरिरहेका छन्।",
  "Incidents nearby": "नजिकका घटनाहरू",
  "No reported incidents nearby.": "नजिकै कुनै घटना रिपोर्ट भएको छैन।",
  "River stations nearby": "नजिकका नदी स्टेशनहरू",
  "No river stations in this radius (or the Rivers filter is off).": "यो दायरामा कुनै नदी स्टेशन छैन (वा नदी फिल्टर बन्द छ)।",
  "Show fewer": "कम देखाउनुहोस्",
  "Show all {n}": "सबै {n} देखाउनुहोस्",
  "Share": "सेयर गर्नुहोस्",
  "Status and link copied": "स्थिति र लिङ्क कपी भयो",
  "Data checked {x}.": "तथ्याङ्क {x} मा जाँचिएको।",
  "Official BIPAD reports only, not a guarantee either way.": "केवल बिपदको आधिकारिक रिपोर्ट, कुनै पनि हिसाबले ग्यारेन्टी होइन।",
  "Reported floods and landslides near a place in Nepal": "नेपालको कुनै स्थान नजिक रिपोर्ट भएका बाढी र पहिरो",

  // data status
  "Offline · showing saved data from {x}": "अफलाइन · {x} को सुरक्षित तथ्याङ्क देखाइँदै",
  "Saved data from {x} · updating…": "{x} को सुरक्षित तथ्याङ्क · अद्यावधिक हुँदैछ…",
  "Updating…": "अद्यावधिक हुँदैछ…",
  "Updated {x}": "अद्यावधिक: {x}",
  "earlier": "अघिको",
  "Refresh": "रिफ्रेस",
  "Refresh data": "तथ्याङ्क रिफ्रेस गर्नुहोस्",
  "Retry": "फेरि प्रयास गर्नुहोस्",
  "Loading official reports…": "आधिकारिक रिपोर्ट लोड हुँदैछ…",
  "Could not load the latest reports. Check your connection and try again.": "पछिल्ला रिपोर्ट लोड हुन सकेन। इन्टरनेट जाँचेर फेरि प्रयास गर्नुहोस्।",
  "Install this app on your phone or computer": "यो एप तपाईंको फोन वा कम्प्युटरमा इन्स्टल गर्नुहोस्",
  "Data from {s}, last checked {x}": "तथ्याङ्कको स्रोत {s}, पछिल्लो जाँच {x}",
  "Official reports only, possibly delayed or incomplete. A lack of reports does not mean there is no hazard. Follow local authorities and call the emergency numbers above if you are in danger. Map © OpenStreetMap contributors.": "केवल आधिकारिक रिपोर्ट, ढिलो वा अपूर्ण हुन सक्छ। रिपोर्ट नहुनुले जोखिम छैन भन्ने होइन। स्थानीय निकायको निर्देशन पालना गर्नुहोस् र खतरामा भए माथिका आपतकालीन नम्बरमा सम्पर्क गर्नुहोस्। नक्सा © OpenStreetMap योगदानकर्ता।",
  "Official reports only, possibly delayed or incomplete. Follow local authorities and call the emergency numbers above if you are in danger.": "केवल आधिकारिक रिपोर्ट, ढिलो वा अपूर्ण हुन सक्छ। स्थानीय निकायको निर्देशन पालना गर्नुहोस् र खतरामा भए माथिका आपतकालीन नम्बरमा सम्पर्क गर्नुहोस्।",

  // time
  "NPT": "नेपाली समय",
  "date only": "मिति मात्र",
  "{n} min ago": "{n} मिनेट अघि",
  "{n} h ago": "{n} घण्टा अघि",
  "{n} days ago": "{n} दिन अघि",

  // items and sources
  "Source": "स्रोत",
  "ID": "आईडी",
  "BIPAD page": "बिपद पृष्ठ",
  "Record": "रेकर्ड",
  "BIPAD's own map page for this kind of data": "यस प्रकारको तथ्याङ्कका लागि बिपदको आफ्नै नक्सा पृष्ठ",
  "This item's entry in BIPAD's public data (JSON)": "बिपदको सार्वजनिक तथ्याङ्कमा यो वस्तुको प्रविष्टि (JSON)",
  "Official record (JSON)": "आधिकारिक रेकर्ड (JSON)",
  "reported": "रिपोर्ट",
  "Reported": "रिपोर्ट भएको",
  "Happened": "भएको",
  "Last reading": "पछिल्लो मापन",
  "No reading": "मापन छैन",
  "Reading": "मापन",
  "Station name in the source": "स्रोतमा स्टेशनको नाम",
  "Inundation": "डुबान",
  "Glacial lake outburst": "हिमताल विस्फोट",
  "Automatic weather station": "स्वचालित मौसम स्टेशन",
  "Rain gauge": "वर्षा मापक",
  "Rain station": "वर्षा स्टेशन",
  "River station": "नदी स्टेशन",
  "Status unavailable": "स्थिति उपलब्ध छैन",
  "Status": "स्थिति",
  "Water level": "पानीको सतह",
  "Warning level": "चेतावनी स्तर",
  "Danger level": "खतरा स्तर",
  "Basin": "जलाधार",
  "BIPAD review": "बिपद समीक्षा",
  "Verified": "प्रमाणित",
  "Not marked verified": "प्रमाणित भनी चिनो लगाइएको छैन",
  "Location is approximate. BIPAD places most reports at ward or municipality level.": "स्थान अनुमानित हो। बिपदले धेरैजसो रिपोर्ट वडा वा नगरपालिका स्तरमा राख्छ।",
  "No current reading, or no warning and danger levels, so a status can't be shown.": "हालको मापन छैन, वा चेतावनी र खतरा स्तर छैन, त्यसैले स्थिति देखाउन सकिँदैन।",
  "Selected item details": "छानिएको वस्तुको विवरण",
  "Close details": "विवरण बन्द गर्नुहोस्",
  "Close (Esc)": "बन्द गर्नुहोस् (Esc)",
  "Check this area": "यो क्षेत्र जाँच्नुहोस्",
  "Incidents within {k} km": "{k} कि.मि. भित्रका घटनाहरू",
  "No other reported incidents within {k} km in the last {d}.": "पछिल्ला {d} मा {k} कि.मि. भित्र अरू कुनै घटना रिपोर्ट भएको छैन।",
  "Showing the nearest 8 of {n}.": "{n} मध्ये सबैभन्दा नजिकका ८ देखाइँदै।",
  "River stations within {k} km": "{k} कि.मि. भित्रका नदी स्टेशनहरू",
  "Rain within {k} km · last {w} h": "{k} कि.मि. भित्रको वर्षा · पछिल्ला {w} घण्टा",
  "No rain recorded in the last {w} h at nearby stations.": "नजिकका स्टेशनमा पछिल्ला {w} घण्टामा वर्षा रेकर्ड भएको छैन।",

  // trend
  "Reports per day": "दैनिक रिपोर्ट",
  "Reports per day within {r} km over the last {n} days: {total} in total": "पछिल्ला {n} दिनमा {r} कि.मि. भित्र दैनिक रिपोर्ट: जम्मा {total}",
  "Within {r} km, last {n} days.": "{r} कि.मि. भित्र, पछिल्ला {n} दिन।",
  "Dates are when BIPAD says it happened, so recent days can still fill in.": "मितिहरू बिपदले घटना भएको भनेको मिति हुन्, त्यसैले हालका दिनमा थप रिपोर्ट थपिन सक्छ।",

  // my places
  "My place": "मेरो स्थान",
  "Checking…": "जाँच गर्दै…",
  "Higher than the last time you looked": "तपाईंले पछिल्लो पटक हेर्दाभन्दा बढी",
  "rose since you last looked": "तपाईंले पछिल्लो पटक हेर्दादेखि बढ्यो",
  "Status within {r} km · last {d}.": "{r} कि.मि. भित्रको स्थिति · पछिल्ला {d}।",
  "Saved on this device only. Updates every time the data refreshes.": "यही उपकरणमा मात्र सुरक्षित। तथ्याङ्क रिफ्रेस हुँदा हरेक पटक अद्यावधिक हुन्छ।",
  "Saved as": "यसरी सुरक्षित:",
  "Remove": "हटाउनुहोस्",
  "You have {n} saved places. Open one and remove it to save this place.": "तपाईंसँग {n} सुरक्षित स्थान छन्। यो स्थान सुरक्षित गर्न एउटा खोलेर हटाउनुहोस्।",
  "Save this place": "यो स्थान सुरक्षित गर्नुहोस्",
  "Name this place": "यो स्थानलाई नाम दिनुहोस्",
  "Save": "सुरक्षित गर्नुहोस्",
  "Cancel": "रद्द गर्नुहोस्",
  "Home": "घर",
  "Family": "परिवार",
  "Work": "कार्यस्थल",
  "Farm": "खेत",

  // forecast and news (not official)
  "Rain forecast": "वर्षाको पूर्वानुमान",
  "Model · not official": "मोडेल · आधिकारिक होइन",
  "Not official": "आधिकारिक होइन",
  "Forecast unavailable right now.": "पूर्वानुमान अहिले उपलब्ध छैन।",
  "Loading forecast…": "पूर्वानुमान लोड हुँदैछ…",
  "{a} mm expected, {b}% chance of rain": "{a} मि.मि. अपेक्षित, वर्षाको सम्भावना {b}%",
  "Today": "आज",
  "Weather-model estimate for this spot (Open-Meteo), not a DHM forecast and not a warning. For official forecasts and warnings see": "यो स्थानका लागि मौसम-मोडेलको अनुमान (Open-Meteo), जल तथा मौसम विज्ञान विभागको पूर्वानुमान वा चेतावनी होइन। आधिकारिक पूर्वानुमान र चेतावनीका लागि हेर्नुहोस्",
  "News": "समाचार",
  "News unavailable right now.": "समाचार अहिले उपलब्ध छैन।",
  "Loading headlines…": "शीर्षकहरू लोड हुँदैछन्…",
  "No recent flood or landslide headlines found.": "बाढी वा पहिरोका हालका शीर्षक भेटिएन।",
  "Headlines mentioning {x}": "{x} उल्लेख भएका शीर्षकहरू",
  "Nothing local found. Latest flood and landslide headlines in Nepal": "स्थानीय केही भेटिएन। नेपालका पछिल्ला बाढी र पहिरोका शीर्षकहरू",
  "Latest flood and landslide headlines in Nepal": "नेपालका पछिल्ला बाढी र पहिरोका शीर्षकहरू",
  "Headlines from public news feeds, not verified by BIPAD or us. Details may be wrong or out of date; check the official reports above.": "सार्वजनिक समाचार फिडका शीर्षक, बिपद वा हामीले प्रमाणित गरेका होइनन्। विवरण गलत वा पुरानो हुन सक्छ; माथिका आधिकारिक रिपोर्ट जाँच्नुहोस्।",
};
